# Generated by Django 4.2.2 on 2023-07-23 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='trailer',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
