# Generated by Django 4.2.2 on 2023-07-19 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('F', 'Filme'), ('S', 'Série')], max_length=1)),
                ('sinopse', models.TextField()),
                ('elenco', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagem', models.ImageField(upload_to='imagens')),
            ],
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
